const fallbackCurrency = 'USD';

const _currencyByCountry = {
  'PK': 'PKR',
  'IN': 'INR',
  'BD': 'BDT',
  'LK': 'LKR',
  'NP': 'NPR',
  'US': 'USD',
  'GB': 'GBP',
  'CA': 'CAD',
  'AU': 'AUD',
  'NZ': 'NZD',
  'AE': 'AED',
  'SA': 'SAR',
  'QA': 'QAR',
  'KW': 'KWD',
  'OM': 'OMR',
  'BH': 'BHD',
  'TR': 'TRY',
  'EG': 'EGP',
  'NG': 'NGN',
  'KE': 'KES',
  'ZA': 'ZAR',
  'JP': 'JPY',
  'KR': 'KRW',
  'CN': 'CNY',
  'SG': 'SGD',
  'MY': 'MYR',
  'ID': 'IDR',
  'PH': 'PHP',
  'TH': 'THB',
  'VN': 'VND',
  'BR': 'BRL',
  'MX': 'MXN',
  'CH': 'CHF',
  'SE': 'SEK',
  'NO': 'NOK',
  'DK': 'DKK',
  'PL': 'PLN',
  'DE': 'EUR',
  'FR': 'EUR',
  'ES': 'EUR',
  'IT': 'EUR',
  'NL': 'EUR',
  'BE': 'EUR',
  'AT': 'EUR',
  'IE': 'EUR',
  'PT': 'EUR',
  'FI': 'EUR',
  'GR': 'EUR',
};

String currencyForCountry(String? countryCode) =>
    _currencyByCountry[countryCode?.toUpperCase()] ?? fallbackCurrency;
